version: "3.8"

services:
  frontend:
    build:
      context: ../manga-web
      args:
        NEXT_PUBLIC_API_URL: https://api.truyenchill.click/
        NEXT_PUBLIC_API_TIMEOUT: 10000
        NEXT_PUBLIC_GA_ID: G-4QGVF81QVH
    container_name: manga-frontend
    ports:
      - "3001:3000"
    restart: always
    networks:
      - nginx-net

  backend:
    build:
      context: ../manga-backend

    container_name: manga-backend
    ports:
      - "3002:3001"
    restart: always
    networks:
      - nginx-net

  bot:
    build:
      context: ../manga-bot
    container_name: manga-bot
    ports:
      - "5003:5003"
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true
